name: Deploy VitePress site to Pages

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - docs/**
      - package.json
      - pnpm-lock.yaml
      - .github/workflows/page.yml

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 22.x ]
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5
      - name: Use pnpm
        run: npm i -g pnpm
      - name: Prepare Dependency
        run: pnpm i --force
      - name: Build with VitePress
        run: pnpm run docs:build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs/.vitepress/dist
          name: 'pages'
      - name: Deploy Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          # 这是文档部署到的分支名称
          branch: pages
          folder: ./docs/.vitepress/dist
      - name: Update Pages
        uses: Gu-ZT/1panel-actions@1.0.2
        with:
          url: ${{ secrets.ONEPANEL_URL }}
          token: ${{ secrets.ONEPANEL_TOKEN }}
          action: runScript
          params: |
            name=更新 lib.anvilcraft.dev
